### ISSUE TITLE
Revise FD charts in reports

### ISSUE THREAD

**Issue by bbartling** [bbartling/open-fdd#16]
@christopherDT  thanks for finding this...

https://stackoverflow.com/questions/3681872/shading-an-area-between-two-points-in-a-matplotlib-plot

Final solution would just be one combined plot:
![image](https://github.com/bbartling/open-fdd/assets/29737117/bbf09d9b-c0bb-48ac-a10f-7500a1cb8981)

https://gist.github.com/christopherDT/129883b6dda40216aabd8a8b74beb818

**Comment by christopherDT** [comment]
This is now included in the PR you just approved. Two main things to be fixed on plotting: 

1. color palette should differ between subplots (gives better contrast between subplots)
2. there's nothing in the legend to indicate that the blue strips are fault locations. Would be good to include that in the legend. I'm not super familiar with the nitty gritty of matplotlib, so not sure how to just add something to the legend.

Bonus: considering changing this to something like seaborn, which has nicer high-level plotting features
