### ISSUE TITLE
update open-fdd column names for schemas alignment

### ISSUE THREAD

**Issue by bsimmons-onboard** [bbartling/open-fdd#25]
Looks like the open-fdd column names have changed since open_fdd_to_schemas.csv

Is this an exhaustive list? If you can provide the full list can help with alignments
DUCT_STATIC_COL
OA_TEMP_COL
MA_TEMP_COL
RA_TEMP_COL
SA_TEMP_COL
OA_DAMPER_COL
RA_DAMPER_COL
COOLING_VALVE_COL
HEATING_VALVE_COL
SA_FAN_SPEED_COL
RA_FAN_SPEED_COL
SA_FLOW_COL
RA_FLOW_COL
OA_FLOW_COL
ZONE_TEMP_COL

**Comment by bbartling** [comment]
Hello,

Yes that is old and needs an update. For now can you just use the `Tutorial for the config dict` inside the README? 

https://github.com/bbartling/open-fdd/tree/master/open_fdd/air_handling_unit#air_handling_unit

![image](https://github.com/user-attachments/assets/68e66992-c59d-4eab-a09f-11cd1ede96da)
